# forms_service.py
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import Flow

import os
from typing import List, Dict

SCOPES = ['https://www.googleapis.com/auth/forms.body']

class FormsService:
    def __init__(self):
        self.creds = None
        self._authenticate()

    def _authenticate(self):
        """Authenticate with Google using OAuth 2.0 (Web Application flow)"""

        if os.path.exists("token.json"):
            self.creds = Credentials.from_authorized_user_file(
                "token.json", SCOPES
            )
            return
        flow = Flow.from_client_secrets_file(
            "credentials.json",
            scopes=SCOPES,
            redirect_uri="http://localhost:8000/auth/google/callback"
        )

        auth_url, _ = flow.authorization_url(
            access_type="offline",
            include_granted_scopes="true",
            prompt="consent"
        )

        print("\n🔐 AUTHORIZE HERE:")
        print(auth_url)

        auth_code = input("\nPaste authorization code here: ").strip()

        flow.fetch_token(code=auth_code)
        self.creds = flow.credentials

        with open("token.json", "w") as token:
            token.write(self.creds.to_json())

    def create_quiz(self, title: str, questions: List[Dict[str, str]]) -> Dict:
        """Create a real Google Form with questions"""
        service = build('forms', 'v1', credentials=self.creds)
        
        # Create a new form
        NEW_FORM = {
            "title": title,
            "description": "Generated by EduSphere AI"
        }
        form = service.forms().create(body=NEW_FORM).execute()
        form_id = form['formId']

        # Add questions
        for q in questions:
            item = {
                "title": q['question'],
                "questionItem": {
                    "question": {
                        "required": True,
                        "choiceQuestion": {
                            "type": "RADIO",
                            "options": [{"value": opt} for opt in q['options']],
                            "shuffle": False
                        }
                    }
                }
            }
            service.forms().batchUpdate(
                formId=form_id,
                body={"requests": [{"createItem": item}]}
            ).execute()

        return {
            "form_id": form_id,
            "form_url": f"https://docs.google.com/forms/d/{form_id}/viewform"
        }
